samples, = glob_wildcards("ressources/data/{sample}/{sample}.fastq.gz")

rule all:
    input:
        "results/common/tel_len.png",
        expand("results/{sample}/nucmer_results/nucmer.png", sample = samples),
        expand("results/{sample}/quast_result/report.pdf", sample = samples),
        directory(expand("results/{sample}/busco_results", sample = samples))

include: "rules/snv_counter.smk"
include: "rules/telomere_length.smk"
include: "rules/assembly_quality_analysis.smk"

rule filtlong:
    """
    This rule filter all reads who has a length below 1000 and aim to get rid of the 10% worst reads.
    """
    input:
        "ressources/data/{sample}/{sample}.fastq.gz"
    output:
        "results/{sample}/{sample}_filtered.fastq"
    params:
        results_directory = "results/{sample}"
    conda:
        "t2tydna"
    log:
        "results/{sample}/logs/{sample}_filtlong.log"
    shell:
        """
        mkdir -p {params.results_directory}
        filtlong --min_length 1000 --keep_percent 90 --target_bases 500000000 {input} > {output} 2>{log}
        """

rule assembly:
    """
    This is the rule making the assembly which is taking all the reads to form the genome.
    Flye is used for the assembly.
    """
    input:
        "results/{sample}/{sample}_filtered.fastq"
    output:
        "results/{sample}/{sample}_genome.fa"
    conda:
        "t2tydna"
    log:
        "results/{sample}/logs/{sample}_assembly.log"
    threads: 32
    shadow: "minimal"
    shell:
        """
        flye --nano-hq {input} --genome-size 12.5m --threads {threads} -i 2 --out-dir results/{wildcards.sample}/flye_tmp 2>{log}
        cp results/{wildcards.sample}/flye_tmp/assembly.fasta {output}
        """

rule racon:
    input:
        assembly = "results/{sample}/{sample}_genome.fa",
        reads = "results/{sample}/{sample}_filtered.fastq"
    output:
        "results/{sample}/{sample}_polished_racon.fa"
    conda:
        "racon"
    log:
        "results/{sample}/logs/{sample}_polishing_racon.log"
    threads: 16
    shell:
        """
        minimap2 -x map-ont {input.assembly} {input.reads} -t {threads} > results/{wildcards.sample}/overlaps.paf
        racon {input.reads} results/{wildcards.sample}/overlaps.paf {input.assembly} -t {threads} > {output}
        """

rule medaka:
    """
    Medaka is a tool to polish the assembly. Basically, it corrects some mistake in the assembly.
    Apparently, it is made for long reads.
    """
    input:
        assembly = "results/{sample}/{sample}_polished_racon.fa",
        reads = "results/{sample}/{sample}_filtered.fastq"
    output:
        "results/{sample}/{sample}_genome_polished.fa"
    conda:
        "medaka"
    log:
        "results/{sample}/logs/{sample}_polishing.log"
    threads: 32
    shell:
        """
        medaka_consensus -i {input.reads} -d {input.assembly} -o results/{wildcards.sample}/medaka_results -m r1041_e82_400bps_sup_v5.2.0 -t {threads}
        mv results/{wildcards.sample}/medaka_results/consensus.fasta {output}
        """

rule correct_chromosome:
    input:
        reference = "ressources/rep/BY.asm01.HP0.nuclear_genome.tidy.fa",
        assembly = "results/{sample}/{sample}_genome_polished.fa"
    output:
        "results/{sample}/ragtag_output_correction/{sample}_genome_polished_corrected.fa"
    conda:
        "test"
    log:
        "results/{sample}/logs/ragtag_correction.log"
    shell:
        """
        ragtag.py correct {input.reference} {input.assembly} -o results/{wildcards.sample}/ragtag_output_correction
        mv results/{wildcards.sample}/ragtag_output_correction/ragtag.correct.fasta {output}
        """

rule chromosome_name:
    """
    After the assembly and polishing, the genome file is made from sequences called contig_42 or contig_35.
    It is better to use the more correct name : chromosome.
    This rule use ragtag to automate this process. By doing so, it is also trying to join the chromosome XII.
    It wasn't part of nicolo's pipeline. Maybe it makes mistake?
    """
    input:
        assembly = "results/{sample}/ragtag_output_correction/{sample}_genome_polished_corrected.fa",
        reference = "ressources/rep/BY.asm01.HP0.nuclear_genome.tidy.fa"
    output:
        "results/{sample}/{sample}_genome_named.fa"
    conda:
        "test"
    log:
        "results/{sample}/logs/{sample}_naming.log"
    shell:
        """
        ragtag.py scaffold {input.reference} {input.assembly} -o results/{wildcards.sample}/ragtag_output/
        mv results/{wildcards.sample}/ragtag_output/ragtag.scaffold.fasta {output}
        """

rule reorder_chromosome:
    """
    Ragtag isn't great, it puts the chromosome 9 between the 4 and the 5. So the mummerplot coming after has some issue.
    Moreover, it adds a "_ragtag" suffix to each chromosome.
    This suffix is removed in this rule and the chromosome get correctly ordered in the fasta files.

    WARNING : I remove also extrachromosomal DNA in this rule for now (since I only get the 16 chromosomes.)
    """
    input:
        "results/{sample}/{sample}_genome_named.fa"
    output:
        "results/{sample}/{sample}_genome_ordered.fa"
    conda:
        "chromosome_management"
    log:
        "results/{sample}/logs/{sample}_naming_reordering.log"
    script:
        "scr/reorder_chromosome_after_naming.py"