configfile: "config/config.yaml"

samples = config.get("samples", [])

rule all:
    input:
        "results/common/tel_len.png",
        expand("results/{sample}/nucmer_results/nucmer.png", sample = samples),
        expand("results/{sample}/quast_result/report.pdf", sample = samples),
        directory(expand("results/{sample}/busco_results", sample = samples))

#nclude: "rules/snv_counter.smk"
include: "rules/telomere_length.smk"
include: "rules/assembly_quality_analysis.smk"
include: "rules/snv_counter.smk"
include: "rules/repeats_analysis.smk"

rule chopper:
    """
    This rule takes our reads and remove the worst (low quality and low size).
    """
    input:
        "ressources/data/{sample}/{sample}.fastq.gz"
    output:
        "results/{sample}/{sample}_filtered.fastq"
    conda:
        "t2tydna"
    shell:
        "chopper -q 15 -l 10000 -i {input} > {output}"

rule filtlong:
    """
    This rule aims to keep a coverage at x80 for speeding up the assembly if there are a lot of reads.
    It prevents big computation time when the coverage is x200 which will leads to negligeable gains compared to x50-x100.
    """
    input:
        "results/{sample}/{sample}_filtered.fastq"
    output:
        "results/{sample}/{sample}_limited_for_assembly.fastq"
    params:
        results_directory = "results/{sample}"
    conda:
        "t2tydna"
    log:
        "results/{sample}/logs/{sample}_filtlong.log"
    shell:
        """
        mkdir -p {params.results_directory}
        filtlong --target_bases 1000000000 {input} > {output}
        """

rule assembly:
    """
    This is the rule making the assembly which is taking all the reads to form the genome.
    Flye is used for the assembly.
    """
    input:
        "results/{sample}/{sample}_limited_for_assembly.fastq"
    output:
        "results/{sample}/{sample}_genome.fa"
    conda:
        "t2tydna"
    log:
        "results/{sample}/logs/{sample}_assembly.log"
    threads: 32
    shadow: "minimal"
    shell:
        """
        flye --nano-hq {input} --genome-size 12.5m --threads {threads} --out-dir results/{wildcards.sample}/flye_tmp 2>{log}
        seqkit seq -g -m 10000 results/{wildcards.sample}/flye_tmp/assembly.fasta > {output}
        """

rule medaka:
    """
    Medaka is a tool to polish the assembly. Basically, it corrects some mistake in the assembly.
    Apparently, it is made for long reads.
    """
    input:
        assembly = "results/{sample}/{sample}_genome.fa",
        reads = "results/{sample}/{sample}_filtered.fastq"
    output:
        "results/{sample}/{sample}_genome_polished.fa"
    conda:
        "medaka"
    log:
        "results/{sample}/logs/{sample}_polishing.log"
    threads: 32
    shell:
        """
        medaka_consensus -i {input.reads} -d {input.assembly} -o results/{wildcards.sample}/medaka_results -m r1041_e82_400bps_sup_v5.2.0 -t {threads}
        mv results/{wildcards.sample}/medaka_results/consensus.fasta {output}
        """

rule mash:
    """
    The scaffolding needs a reference. This rules aims to give the best references among those that are in the /rep folder in ressources.
    """
    input:
        assembly = "results/{sample}/{sample}_genome_polished.fa",
        possible_references = config["references"]
    output:
        reference = "results/{sample}/reference_sample.fa"
    conda:
        "t2tydna"
    log:
        "results/{sample}/logs/{sample}_mash.log"
    shell:
        """
        BEST_PATH=$(mash dist {input.assembly} {input.possible_references} | sort -gk3 | head -n 1 | cut -f1)
        echo "$BEST_PATH"
        cp "$BEST_PATH" {output}
        """

rule correct_chromosome:
    input:
        reference = config["references"],
        assembly = "results/{sample}/{sample}_genome_polished.fa"
    output:
        "results/{sample}/ragtag_output_correction/{sample}_genome_polished_corrected.fa"
    conda:
        "test"
    log:
        "results/{sample}/logs/ragtag_correction.log"
    shell:
        """
        ragtag.py correct {input.reference} {input.assembly} -o results/{wildcards.sample}/ragtag_output_correction
        mv results/{wildcards.sample}/ragtag_output_correction/ragtag.correct.fasta {output}
        """

rule chromosome_name:
    """
    After the assembly and polishing, the genome file is made from sequences called contig_42 or contig_35.
    It is better to use the more correct name : chromosome.
    This rule use ragtag to automate this process. By doing so, it is also trying to join the chromosome XII.
    It wasn't part of nicolo's pipeline.
    """
    input:
        assembly = "results/{sample}/ragtag_output_correction/{sample}_genome_polished_corrected.fa",
        reference = config["references"]
    output:
        "results/{sample}/{sample}_genome_named.fa"
    conda:
        "test"
    log:
        "results/{sample}/logs/{sample}_naming.log"
    shell:
        """
        ragtag.py scaffold {input.reference} {input.assembly} -o results/{wildcards.sample}/ragtag_output/
        mv results/{wildcards.sample}/ragtag_output/ragtag.scaffold.fasta {output}
        """

rule reorder_chromosome:
    """
    Ragtag adds a "_ragtag" suffix to each chromosome.
    This suffix is removed in this rule and the chromosome get correctly ordered in the fasta files.

    WARNING : I remove also extrachromosomal DNA in this rule for now (since I only get the 16 chromosomes.)
    """
    input:
        "results/{sample}/{sample}_genome_named.fa"
    output:
        "results/{sample}/{sample}_genome_ordered.fa"
    conda:
        "chromosome_management"
    log:
        "results/{sample}/logs/{sample}_naming_reordering.log"
    script:
        "scr/reorder_chromosome_after_naming.py"
