import os

configfile: "config/config.yaml"

samples = config.get("samples", [])

rule all:
    input:
        expand("results/{sample}/summary_variant_counter_cleaned.csv", sample = samples)


include: "rules/telomere_length.smk"
include: "rules/assembly_quality_analysis.smk"
include: "rules/snv_counter.smk"
include: "rules/repeats_analysis.smk"
include: "rules/aneuploidie_analysis.smk"

# rule convert_to_fastq:
#     input:
#         reads = "ressources/data/{sample}/{sample}.bam"
#     output:
#         "ressources/data/{sample}/{sample}.fastq.gz"
#     conda:
#         "t2tydna"
#     shell:
#         """
#         samtools fastq {input.reads} | gzip > {output}
#         """

rule chopper:
    """
    This rule takes our reads and remove the worst (low quality and low size).
    """
    input:
        "ressources/data/{sample}/{sample}.fastq.gz"
    output:
       "results/{sample}/{sample}_filtered.fastq"
    conda:
        "envs/chopper.yaml"
    log:
        "results/{sample}/logs/{sample}_chopper.log"
    shell:
        "chopper -q 15 -l 10000 -i {input} > {output} 2>{log}"

rule filtlong:
    """
    This rule aims to keep a coverage at x80 for speeding up the assembly if there are a lot of reads.
    It prevents big computation time when the coverage is x200 which will leads to negligeable gains compared to x50-x100.
    """
    input:
        "results/{sample}/{sample}_filtered.fastq"
    output:
        temp("results/{sample}/{sample}_limited_for_assembly.fastq")
    params:
        results_directory = "results/{sample}"
    conda:
        "envs/filtlong.yaml"
    log:
        "results/{sample}/logs/{sample}_filtlong.log"
    shell:
        """
        mkdir -p {params.results_directory}
        filtlong --target_bases 1000000000 {input} > {output} 2>{log}
        """

rule assembly:
    """
    This is the rule making the assembly which is taking all the reads to form the genome.
    Flye is used for the assembly.
    """
    input:
        "results/{sample}/{sample}_limited_for_assembly.fastq"
    output:
        "results/{sample}/{sample}_genome.fa"
    conda:
        "envs/assembly.yaml"
    log:
        "results/{sample}/logs/{sample}_assembly.log"
    threads: 32
    shadow: "minimal"
    shell:
        """
        flye --nano-hq {input} --genome-size 12.5m --threads {threads} --out-dir results/{wildcards.sample}/flye_tmp 2>{log}
        seqkit seq -g -m 10000 results/{wildcards.sample}/flye_tmp/assembly.fasta > {output}
        """

rule medaka:
    """
    Medaka is a tool to polish the assembly. Basically, it corrects some mistake in the assembly.
    Apparently, it is made for long reads.
    """
    input:
        assembly = "results/{sample}/{sample}_genome.fa",
        reads = "results/{sample}/{sample}_filtered.fastq"
    output:
        genome = "results/{sample}/{sample}_genome_polished.fa",
    conda:
        "envs/medaka.yaml"
    log:
        "results/{sample}/logs/{sample}_polishing.log"
    threads: 32
    shadow: "minimal"
    shell:
        """
        medaka_consensus -b 50 -i {input.reads} -d {input.assembly} -o medaka_results -m r1041_e82_400bps_sup_v5.2.0 -t {threads}
        mv medaka_results/consensus.fasta {output.genome}
        """

rule mash:
    """
    The scaffolding needs a reference. This rules aims to give the best references among those that are in the /rep folder in ressources.
    """
    input:
        assembly = "results/{sample}/{sample}_genome_polished.fa",
        possible_references = config["references"]
    output:
        reference = "results/{sample}/reference_sample.fa",
        annotation = "results/{sample}/reference_annotation.gff3"
    conda:
        "envs/mash.yaml"
    log:
        "results/{sample}/logs/{sample}_mash.log"
    shell:
        """
        BEST_PATH=$(mash dist {input.assembly} {input.possible_references} | sort -gk3 | head -n 1 | cut -f2)
        echo "$BEST_PATH"
        cp "$BEST_PATH" {output.reference}
        cp "${{BEST_PATH//.fa/.gff3}}" {output.annotation}
        """

rule correct_chromosome:
    input:
        reference = "results/{sample}/reference_sample.fa",
        assembly = "results/{sample}/{sample}_genome_polished.fa"
    output:
        temp("results/{sample}/{sample}_genome_polished_corrected.fa")
    conda:
        "envs/ragtag.yaml"
    log:
        "results/{sample}/logs/ragtag_correction.log"
    shadow: "minimal"
    shell:
        """
        ragtag.py correct {input.reference} {input.assembly} -o ragtag_output_correction
        mv ragtag_output_correction/ragtag.correct.fasta {output}
        """

rule chromosome_name:
    """
    After the assembly and polishing, the genome file is made from sequences called contig_42 or contig_35.
    It is better to use the more correct name : chromosome.
    This rule use ragtag to automate this process. By doing so, it is also trying to join the chromosome XII.
    It wasn't part of nicolo's pipeline.
    """
    input:
        assembly = "results/{sample}/{sample}_genome_polished_corrected.fa",
        reference = "results/{sample}/reference_sample.fa"
    output:
        temp("results/{sample}/{sample}_genome_named.fa")
    conda:
        "envs/ragtag.yaml"
    log:
        "results/{sample}/logs/{sample}_naming.log"
    shadow: "minimal"
    shell:
        """
        ragtag.py scaffold {input.reference} {input.assembly} -o ragtag_output/ 2>{log}
        mv ragtag_output/ragtag.scaffold.fasta {output}
        """

rule reorder_chromosome:
    """
    Ragtag adds a "_ragtag" suffix to each chromosome.
    This suffix is removed in this rule and the chromosome get correctly ordered in the fasta files.

    WARNING : I remove also extrachromosomal DNA in this rule for now (since I only get the 16 chromosomes.)
    """
    input:
        "results/{sample}/{sample}_genome_named.fa"
    output:
        "results/{sample}/{sample}_genome_ordered.fa"
    conda:
        "envs/reorder_chromosome.yaml"
    log:
        "results/{sample}/logs/{sample}_naming_reordering.log"
    script:
        "scr/reorder_chromosome_after_naming.py"

rule annotate:
    """
    Using liftoff and a reference to get the coordinate of the different genes.
    """
    input:
        target = "results/{sample}/{sample}_genome_ordered.fa",
        ref = "results/{sample}/reference_sample.fa",
        annotation = "results/AG0/reference_annotation.gff3"
    output:
        "results/{sample}/{sample}_annotation.gff3"
    conda:
        "envs/liftoff.yaml"
    log:
        "results/{sample}/logs/{sample}_annotation.log"
    shadow: "minimal"
    shell:
        "liftoff {input.target} {input.ref} -g {input.annotation} -o {output} 2>{log}"
    

rule multi_qc:
    input:
        "results/{sample}/nucmer_results/nucmer_mqc.png",
        "results/{sample}/busco_results/short_summary.specific.saccharomycetaceae_odb12.busco_results.json",
        "results/{sample}/quast_results/report.pdf"
    output:
        "results/{sample}/multiqc_report.html"
    conda:
        "envs/multiqc.yaml"
    shell:
        "multiqc results/{wildcards.sample} --no-ai --clean-up --no-data-dir --outdir results/{wildcards.sample}"