samples:
  - G50_25_DOXY
  - G100_25_DOXY
  - G150_25_DOXY
  - G600_CAS_25_DOXY_Rep1
  - G600_CAS_25_DOXY_Rep2

references:
  - "ressources/rep/CAS_1a.asm01.HP0.nuclear_genome.tidy.fa"
#  - "ressources/rep/BY.asm01.HP0.nuclear_genome.tidy.fa"

annotation:
 - "ressources/rep/CAS_1a.asm01.HP0.nuclear_genome.tidy.gff3"