samples:
 - AG0
 - G50_1_DOXY

references:
  - "ressources/rep/CAS_1a.asm01.HP0.nuclear_genome.tidy.fa"
  - "ressources/rep/BY.asm01.HP0.nuclear_genome.tidy.fa"
  - "ressources/rep/YPS128.asm01.HP0.nuclear_genome.tidy.fa"
  - "ressources/rep/DBVPG6765.asm01.HP0.nuclear_genome.tidy.fa"

annotation:
 - "ressources/rep/CAS_1a.asm01.HP0.nuclear_genome.tidy.gff3"
 - "ressources/rep/BY.asm01.HP0.nuclear_genome.tidy.gff3"